import './globals.css';
import { Inter, Nunito, Raleway } from 'next/font/google';

export const metadata = {
  title: "FluentFocus",
  description: "Generated by create next app",
};

const inter = Inter({ subsets:['latin'], variable: '--font-inter' });
const nunito = Nunito({ subsets:['latin'], variable: '--font-nunito' });
const raleway = Raleway ({ subsets:['latin'], variable: '--font-raleway' });

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.variable} ${nunito.variable} ${raleway.variable} font-sans`}
      >
        {children}
      </body>
    </html>
  );
}
